# Generated by Django 5.0.6 on 2024-05-21 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('image', models.TextField(blank=True, default='https://avatars.mds.yandex.net/i?id=ee54224ac5c66e2f0ce002ee3d9ca1e178e490c3-12421615-images-thumbs&n=13')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reaction', models.IntegerField()),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.theme')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('written_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.post')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.user')),
            ],
        ),
    ]
