# Generated by Django 5.0.6 on 2024-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Comment',
        ),
    ]
