# Generated by Django 5.0.6 on 2024-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_rename_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reaction',
            field=models.IntegerField(null=True),
        ),
    ]
